version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Konteyner içindeki port ve dışarıya açılan port
    volumes:
      - .:/app  # Yerel dosyaları konteynıra bağlayın
    environment:
      - ENVIRONMENT=development
    restart: always
